name: Singularity CI & GHCR

on:
  push:
    branches:
      - main
    paths:
      - "lpa.singularity"
      - "py-requirements.txt"

  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # needed to push to GHCR

    steps:
      - uses: actions/checkout@v5

      - name: Install Singularity
        run: |
          sudo apt update
          sudo apt install -y singularity-ce

      - name: Build Singularity image
        if: github.ref == 'refs/heads/main'
        run: |
          singularity build lpa.simg lpa.singularity

      - name: Log in to GHCR
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | singularity remote login -u ${{ github.actor }} --password-stdin oras://ghcr.io

      - name: Push Singularity image to GHCR
        if: github.ref == 'refs/heads/main'
        run: |
          singularity push lpa.simg oras://ghcr.io/${{ github.repository }}/lpa:latest
